# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='NewNotes',
        ),
    ]
