# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160729_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newnotes',
            name='note',
        ),
        migrations.DeleteModel(
            name='NewNotes',
        ),
    ]
