# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160729_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note')),
            ],
        ),
    ]
